'use client'

import Navigation from '@/app/components/Navigation'
import Footer from '@/app/components/Footer'
import { useState } from 'react'
import Link from 'next/link'
import { 
  ChevronRight, BarChart3, Users, AlertCircle, TrendingUp, Clock, Shield, 
  Target, Zap, Brain, CheckCircle, Award, MessageCircle, Settings,
  UserCheck, TrendingDown, AlertTriangle, Star, Calendar, DollarSign
} from 'lucide-react'

export default function ServiceDeskManagementPage() {
  const [activeModule, setActiveModule] = useState('assignment')

  const modules = [
    {
      id: 'assignment',
      title: 'AI Ticket Assignment',
      icon: <Target className="w-8 h-8" />,
      color: 'from-blue-600 to-cyan-500',
      description: 'Intelligent ticket routing based on skills and workload'
    },
    {
      id: 'escalations',
      title: 'Escalations Board',
      icon: <AlertTriangle className="w-8 h-8" />,
      color: 'from-red-600 to-orange-500',
      description: 'Human and AI-generated escalation tracking'
    },
    {
      id: 'client-health',
      title: 'Client Health',
      icon: <Shield className="w-8 h-8" />,
      color: 'from-green-600 to-emerald-500',
      description: 'Satisfaction and profitability monitoring'
    },
    {
      id: 'team-performance',
      title: 'Team Performance',
      icon: <Award className="w-8 h-8" />,
      color: 'from-purple-600 to-pink-500',
      description: 'Analytics with weekly coaching insights'
    }
  ]

  const moduleDetails = {
    assignment: {
      subtitle: 'Intelligent Resource Matching',
      video: '/triage-video.mp4',
      features: [
        {
          icon: <Brain className="w-6 h-6 text-blue-400" />,
          title: 'Skills Analysis',
          description: 'AI analyzes ticket requirements and matches them to engineer skills and certifications needed to properly address the issue.'
        },
        {
          icon: <BarChart3 className="w-6 h-6 text-blue-400" />,
          title: 'Workload Assessment',
          description: 'System evaluates current engineer workload to ensure optimal distribution and prevent burnout.'
        },
        {
          icon: <Target className="w-6 h-6 text-blue-400" />,
          title: 'Confidence Ranking',
          description: 'Provides 2-3 engineer suggestions with AI confidence levels for each assignment recommendation.'
        },
        {
          icon: <Zap className="w-6 h-6 text-blue-400" />,
          title: 'Automated Assignment',
          description: 'Once configured, automatically assigns tickets when AI confidence threshold is met (e.g., 90% certainty).'
        }
      ],
      benefits: [
        'Reduce ticket assignment time from minutes to seconds',
        'Improve first-time resolution rates by 40%',
        'Balance workload across engineering team',
        'Ensure tickets go to most qualified engineers'
      ],
      process: [
        'New ticket arrives in ConnectWise Manage',
        'AI analyzes ticket content and requirements',
        'System evaluates engineer skills and current workload',
        'Provides ranked assignment suggestions with confidence scores',
        'Manager approves or system auto-assigns based on threshold'
      ]
    },
    escalations: {
      subtitle: 'Proactive Issue Detection',
      video: null, // escalations video coming soon
      features: [
        {
          icon: <Users className="w-6 h-6 text-red-400" />,
          title: 'Human Escalations',
          description: 'Track escalations generated by engineers who recognize they need assistance or are in trouble.'
        },
        {
          icon: <Brain className="w-6 h-6 text-red-400" />,
          title: 'AI-Generated Alerts',
          description: 'AI analyzes technical solution strength, communication cadence, and progress patterns to identify at-risk tickets.'
        },
        {
          icon: <MessageCircle className="w-6 h-6 text-red-400" />,
          title: 'Communication Analysis',
          description: 'Monitors frequency and clarity of ticket updates to ensure clients stay informed and engaged.'
        },
        {
          icon: <Clock className="w-6 h-6 text-red-400" />,
          title: 'End-User Impact',
          description: 'Assesses disruption to end user work day and prioritizes escalations based on business impact.'
        }
      ],
      benefits: [
        'Identify problem tickets before they become critical',
        'Reduce escalations by 30% through early intervention',
        'Improve client satisfaction scores',
        'Enable proactive management decisions'
      ],
      process: [
        'System continuously monitors all active tickets',
        'AI scores tickets based on multiple risk variables',
        'Escalations board highlights at-risk tickets',
        'Managers receive alerts for tickets needing attention',
        'Take immediate action to prevent client issues'
      ]
    },
    'client-health': {
      subtitle: 'Comprehensive Client Monitoring',
      video: null, // client health video coming soon
      features: [
        {
          icon: <Star className="w-6 h-6 text-green-400" />,
          title: 'Satisfaction Scoring',
          description: 'Numerical assessment of CSAT scores and post-ticket survey responses to gauge client happiness.'
        },
        {
          icon: <BarChart3 className="w-6 h-6 text-green-400" />,
          title: 'Resolution Tracking',
          description: 'Monitor number of tickets resolved and track resolution patterns to identify service trends.'
        },
        {
          icon: <AlertTriangle className="w-6 h-6 text-green-400" />,
          title: 'Escalation Analysis',
          description: 'Track escalation frequency as an indicator of potentially troublesome client relationships.'
        },
        {
          icon: <DollarSign className="w-6 h-6 text-green-400" />,
          title: 'Profitability Gauge',
          description: 'Compare labor hours expended against budgeted hours to determine client profitability (no complex financial metrics).'
        }
      ],
      benefits: [
        'Identify at-risk client relationships early',
        'Focus attention on most profitable clients',
        'Improve overall client satisfaction scores',
        'Reduce client churn through proactive intervention'
      ],
      process: [
        'System aggregates data from multiple touchpoints',
        'Calculates client health scores in real-time',
        'Identifies clients requiring immediate attention',
        'Provides actionable recommendations for improvement',
        'Tracks progress over time with trend analysis'
      ]
    },
    'team-performance': {
      subtitle: 'Engineer Development & Recognition',
      video: null, // team performance video coming soon
      features: [
        {
          icon: <TrendingUp className="w-6 h-6 text-purple-400" />,
          title: 'Performance Metrics',
          description: 'Track work output, resolution speed, and quality metrics for each engineer on your team.'
        },
        {
          icon: <Star className="w-6 h-6 text-purple-400" />,
          title: 'CSAT Tracking',
          description: 'Monitor individual engineer satisfaction scores from client feedback and post-ticket surveys.'
        },
        {
          icon: <AlertCircle className="w-6 h-6 text-purple-400" />,
          title: 'Escalation Monitoring',
          description: 'Track escalation frequency per engineer to identify coaching opportunities and high performers.'
        },
        {
          icon: <Award className="w-6 h-6 text-purple-400" />,
          title: 'Weekly Insights',
          description: 'Rotating weekly/bi-weekly insights with recognition recommendations and coaching suggestions.'
        }
      ],
      benefits: [
        'Identify top performers for recognition',
        'Spot engineers needing additional coaching',
        'Improve overall team performance',
        'Make data-driven personnel decisions'
      ],
      process: [
        'System analyzes all engineer activities and outcomes',
        'Generates individual performance scorecards',
        'Identifies patterns in repeat service calls',
        'Provides weekly coaching and recognition insights',
        'Tracks team performance trends over time'
      ]
    }
  }

  return (
    <div className="min-h-screen bg-black text-white">
      <Navigation />

      {/* Hero Section */}
      <section className="px-6 py-20 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-blue-900/10 via-transparent to-purple-900/10"></div>
        <div className="max-w-5xl mx-auto text-center relative z-10">
          <div className="inline-flex items-center gap-2 bg-blue-500/10 border border-blue-500/20 px-4 py-2 rounded-full mb-6">
            <BarChart3 className="w-4 h-4 text-blue-400" />
            <span className="text-sm font-medium text-blue-400">Manager App</span>
          </div>
          <h1 className="text-5xl md:text-7xl font-bold mb-8 bg-gradient-to-r from-white via-blue-100 to-white bg-clip-text text-transparent">
            Service Desk Management
          </h1>
          <p className="text-xl md:text-2xl text-gray-300 mb-4 max-w-3xl mx-auto leading-relaxed">
            Four powerful modules to optimize ticket assignment, track escalations, monitor client health, and analyze team performance
          </p>
          <p className="text-gray-400 max-w-2xl mx-auto mb-8">
            The Manager App provides real-time insights and AI-powered optimization for service managers, 
            with integrated ConnectWise Manage tracking and automated decision support.
          </p>
          <div className="flex justify-center">
            <Link
              href="/contact"
              className="inline-flex items-center gap-2 bg-gradient-to-r from-blue-600 to-cyan-500 px-8 py-4 rounded-full font-semibold hover:opacity-90 transform hover:scale-105 transition-all"
            >
              See Manager App Demo
              <ChevronRight className="w-5 h-5" />
            </Link>
          </div>
        </div>
      </section>

      {/* Four Modules Overview */}
      <section className="px-6 py-16 bg-gray-900/50">
        <div className="max-w-7xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-4">Four Integrated Modules</h2>
          <p className="text-xl text-gray-300 text-center mb-12 max-w-3xl mx-auto">
            Each module works together to provide comprehensive service desk management and optimization
          </p>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {modules.map((module, index) => (
              <div 
                key={module.id}
                className={`bg-gradient-to-br ${module.color} p-8 rounded-xl border border-gray-800 hover:border-gray-600 transition-all transform hover:-translate-y-1 cursor-pointer animate-fadeIn`}
                style={{ animationDelay: `${index * 0.1}s` }}
                onClick={() => setActiveModule(module.id)}
              >
                <div className="text-white mb-4">{module.icon}</div>
                <h3 className="text-xl font-bold mb-3 text-white">{module.title}</h3>
                <p className="text-white/90 text-sm">{module.description}</p>
                <div className="mt-4 flex items-center text-white/80 text-sm">
                  <span>Learn more</span>
                  <ChevronRight className="w-4 h-4 ml-1" />
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Module Selector */}
      <section className="px-6 py-16">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-12">Detailed Module Overview</h2>
          
          {/* Module Navigation */}
          <div className="flex flex-wrap justify-center gap-4 mb-12">
            {modules.map((module) => (
              <button
                key={module.id}
                onClick={() => setActiveModule(module.id)}
                className={`flex items-center gap-2 px-6 py-3 rounded-full transition-all ${
                  activeModule === module.id
                    ? `bg-gradient-to-r ${module.color} text-white`
                    : 'bg-gray-800 hover:bg-gray-700 text-gray-300'
                }`}
              >
                {module.icon}
                <span className="font-medium">{module.title}</span>
              </button>
            ))}
          </div>

          {/* Active Module Details */}
          <div className="bg-gray-900/50 border border-gray-800 rounded-2xl p-8">
            <div className="text-center mb-8">
              <h3 className="text-3xl font-bold mb-2">
                {modules.find(m => m.id === activeModule)?.title}
              </h3>
              <p className="text-xl text-gray-300">
                {moduleDetails[activeModule as keyof typeof moduleDetails]?.subtitle}
              </p>
            </div>

            {/* Module Video */}
            {moduleDetails[activeModule as keyof typeof moduleDetails]?.video && (
              <div className="mb-10">
                <div className="relative rounded-xl overflow-hidden shadow-2xl shadow-blue-500/20 border border-gray-700 max-w-4xl mx-auto">
                  <video
                    key={moduleDetails[activeModule as keyof typeof moduleDetails]?.video}
                    className="w-full h-auto"
                    controls
                    preload="metadata"
                  >
                    <source src={moduleDetails[activeModule as keyof typeof moduleDetails]?.video || ''} type="video/mp4" />
                    Your browser does not support the video tag.
                  </video>
                </div>
              </div>
            )}

            <div className="grid lg:grid-cols-2 gap-12">
              {/* Features */}
              <div>
                <h4 className="text-2xl font-semibold mb-6 flex items-center gap-2">
                  <Settings className="w-6 h-6 text-blue-400" />
                  Key Features
                </h4>
                <div className="space-y-6">
                  {moduleDetails[activeModule as keyof typeof moduleDetails]?.features.map((feature, index) => (
                    <div key={index} className="flex gap-4">
                      <div className="flex-shrink-0 bg-gray-800 p-3 rounded-lg">
                        {feature.icon}
                      </div>
                      <div>
                        <h5 className="font-semibold mb-2">{feature.title}</h5>
                        <p className="text-gray-400 text-sm leading-relaxed">{feature.description}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Benefits & Process */}
              <div className="space-y-8">
                {/* Benefits */}
                <div>
                  <h4 className="text-2xl font-semibold mb-6 flex items-center gap-2">
                    <TrendingUp className="w-6 h-6 text-green-400" />
                    Key Benefits
                  </h4>
                  <div className="space-y-3">
                    {moduleDetails[activeModule as keyof typeof moduleDetails]?.benefits.map((benefit, index) => (
                      <div key={index} className="flex items-start gap-3">
                        <CheckCircle className="w-5 h-5 text-green-400 mt-0.5 flex-shrink-0" />
                        <span className="text-gray-300">{benefit}</span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Process */}
                <div>
                  <h4 className="text-2xl font-semibold mb-6 flex items-center gap-2">
                    <Clock className="w-6 h-6 text-purple-400" />
                    How It Works
                  </h4>
                  <div className="space-y-4">
                    {moduleDetails[activeModule as keyof typeof moduleDetails]?.process.map((step, index) => (
                      <div key={index} className="flex gap-4">
                        <div className="flex-shrink-0 w-6 h-6 bg-purple-600 text-white rounded-full flex items-center justify-center text-sm font-bold">
                          {index + 1}
                        </div>
                        <span className="text-gray-300">{step}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Integration Section */}
      <section className="px-6 py-16 bg-gray-900/50">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-4">ConnectWise Manage Integration</h2>
          <p className="text-xl text-gray-300 text-center mb-12 max-w-3xl mx-auto">
            All Manager App modules integrate seamlessly with your existing ConnectWise Manage workflow
          </p>
          
          <div className="grid md:grid-cols-3 gap-8">
            <div className="bg-black/50 border border-gray-800 rounded-lg p-6 text-center">
              <div className="w-16 h-16 bg-blue-600 rounded-full flex items-center justify-center mx-auto mb-4">
                <Zap className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-xl font-semibold mb-3">Real-Time Data</h3>
              <p className="text-gray-400">
                All tracking and insights pull directly from ConnectWise Manage data in real-time
              </p>
            </div>
            
            <div className="bg-black/50 border border-gray-800 rounded-lg p-6 text-center">
              <div className="w-16 h-16 bg-green-600 rounded-full flex items-center justify-center mx-auto mb-4">
                <Settings className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-xl font-semibold mb-3">No Workflow Changes</h3>
              <p className="text-gray-400">
                Manager App works as an overlay - your existing processes remain unchanged
              </p>
            </div>
            
            <div className="bg-black/50 border border-gray-800 rounded-lg p-6 text-center">
              <div className="w-16 h-16 bg-purple-600 rounded-full flex items-center justify-center mx-auto mb-4">
                <BarChart3 className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-xl font-semibold mb-3">Automated Insights</h3>
              <p className="text-gray-400">
                Weekly coaching and recognition insights delivered automatically to managers
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ROI Section */}
      <section className="px-6 py-16">
        <div className="max-w-4xl mx-auto">
          <div className="bg-gradient-to-r from-blue-900/20 to-purple-900/20 border border-blue-500/30 rounded-2xl p-8 md:p-12 text-center">
            <h2 className="text-3xl font-bold mb-4">Transform Your Service Desk Operations</h2>
            <p className="text-xl text-gray-300 mb-8">
              MSPs using the Manager App see immediate improvements in efficiency, client satisfaction, and team performance
            </p>
            
            <div className="grid md:grid-cols-3 gap-6 mb-8">
              <div className="bg-black/30 rounded-lg p-6">
                <div className="text-3xl font-bold text-blue-400 mb-2">40%</div>
                <div className="text-sm text-gray-400">Faster Ticket Assignment</div>
              </div>
              <div className="bg-black/30 rounded-lg p-6">
                <div className="text-3xl font-bold text-green-400 mb-2">30%</div>
                <div className="text-sm text-gray-400">Reduction in Escalations</div>
              </div>
              <div className="bg-black/30 rounded-lg p-6">
                <div className="text-3xl font-bold text-purple-400 mb-2">25%</div>
                <div className="text-sm text-gray-400">Improvement in Client Satisfaction</div>
              </div>
            </div>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href="/contact"
                className="inline-flex items-center gap-2 bg-gradient-to-r from-blue-600 to-purple-600 px-8 py-4 rounded-full font-semibold hover:opacity-90 transition-opacity"
              >
                Schedule a Demo
                <ChevronRight className="w-5 h-5" />
              </Link>
              <Link
                href="/solutions/engineer-efficiency"
                className="inline-flex items-center gap-2 border border-blue-500/30 px-8 py-4 rounded-full font-semibold hover:bg-blue-500/10 transition-colors"
              >
                See Engineer App
              </Link>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  )
}